# ██╗  ██╗ █████╗       ██╗    ██╗   ██╗██████╗ 
# ██║ ██╔╝██╔══██╗      ██║    ██║   ██║╚════██╗
# █████╔╝ ███████║      ██║    ██║   ██║ █████╔╝
# ██╔═██╗ ██╔══██║ ██   ██║    ╚██╗ ██╔╝██╔═══╝ 
# ██║  ██╗██║  ██║ ╚█████╔╝     ╚████╔╝ ███████╗
# ╚═╝  ╚═╝╚═╝  ╚═╝  ╚════╝       ╚═══╝  ╚══════╝
# >> ARCH LINUX // KAJ V2 // DOCKER COMPOSE <<

# === [ SERVICES CONFIGURATION ] ===
services:
  db:
    # --- Image & Restart Policy ---
    image: mysql:8.0
    restart: always

    # --- Port Mapping ---
    ports:
      - "3307:3306"

    # --- Environment Credentials ---
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}

    # --- Persistent Storage ---
    volumes:
      - db_data:/var/lib/mysql

# === [ VOLUMES DECLARATION ] ===
volumes:
  db_data: